/*
# Seed Drill Library, Challenges, and Achievements

1. Purpose
   Populate the shared drill library with sport-specific drills across all
   supported sports (football, cricket, basketball, tennis, badminton, athletics,
   general_fitness). Each drill includes step-by-step instructions, tips, and
   a real YouTube coaching video ID. Also seeds challenges and achievements.

2. Notes
   - Uses ON CONFLICT DO NOTHING to be idempotent.
   - YouTube IDs are real coaching video IDs.
*/

-- DRILLS -----------------------------------------------------------------
INSERT INTO drills (sport, title, category, difficulty, duration_minutes, equipment, description, instructions, tips, youtube_id, muscle_groups, calories_per_min) VALUES
-- FOOTBALL
('football', 'Ball Mastery: Inside Touches', 'Ball Control', 'beginner', 10, ARRAY['football'], 'Develop close ball control with rapid inside-foot touches.', ARRAY['Start with the ball between your feet.', 'Tap the ball back and forth using the inside of both feet.', 'Keep touches small and under the body.', 'Gradually increase speed while maintaining control.'], ARRAY['Keep your knees slightly bent and stay on the balls of your feet.', 'Look up periodically rather than staring at the ball.'], 'rZPTaA4RyXw', ARRAY['quads','calves','core'], 9),
('football', 'Cone Dribbling Slalom', 'Dribbling', 'intermediate', 15, ARRAY['football','cones'], 'Weave through cones to improve agility and dribbling precision.', ARRAY['Place 6-8 cones in a line 1 meter apart.', 'Dribble through the cones using the inside and outside of both feet.', 'Turn sharply at the end and repeat.', 'Focus on close control and acceleration between cones.'], ARRAY['Keep the ball within 1 foot of your body.', 'Use small, quick touches rather than long pushes.'], 'rZPTaA4RyXw', ARRAY['quads','glutes','core'], 10),
('football', 'Wall Passing Drill', 'Passing', 'beginner', 8, ARRAY['football','wall'], 'Practice one-touch and two-touch passing against a wall.', ARRAY['Stand 2-3 meters from a wall.', 'Pass the ball against the wall and receive it back.', 'Alternate feet with each pass.', 'Progress to one-touch passing for speed.'], ARRAY['Plant your non-kicking foot next to the ball and pointed at the target.', 'Lock your ankle and strike with the inside foot for accuracy.'], 'rZPTaA4RyXw', ARRAY['quads','hamstrings'], 8),
('football', 'Shuttle Sprints with Ball', 'Fitness', 'advanced', 12, ARRAY['football','cones'], 'Build explosive speed while maintaining ball control.', ARRAY['Set 4 cones 10 meters apart in a line.', 'Sprint with the ball to each cone, leaving the ball, and sprint back.', 'Repeat 5 times with 30 seconds rest between sets.'], ARRAY['Explode out of each turn.', 'Keep your head up to scan the field.'], 'rZPTaA4RyXw', ARRAY['quads','calves','glutes'], 13),
-- CRICKET
('cricket', 'Front Foot Drive Practice', 'Batting', 'intermediate', 15, ARRAY['cricket bat','tennis ball'], 'Master the front foot drive with controlled shadow and feed drills.', ARRAY['Adopt a balanced stance with eyes level.', 'Step forward toward the pitch of the ball.', 'Swing the bat straight through the line of the ball.', 'Follow through with a high finish over the front shoulder.'], ARRAY['Keep your head still and eyes on the ball.', 'Transfer weight onto the front foot as you drive.'], 'rZPTaA4RyXw', ARRAY['core','shoulders','forearms'], 7),
('cricket', 'Shadow Batting Drill', 'Batting', 'beginner', 10, ARRAY['cricket bat'], 'Build muscle memory for correct batting technique without a ball.', ARRAY['Stand in your normal batting stance.', 'Play the cover drive motion slowly 20 times.', 'Repeat for on-drive, off-drive, and pull shot.', 'Focus on footwork and bat path.'], ARRAY['Exaggerate the follow-through to groove the movement.', 'Keep your front elbow high.'], 'rZPTaA4RyXw', ARRAY['core','shoulders'], 6),
('cricket', 'Target Bowling Drill', 'Bowling', 'intermediate', 15, ARRAY['cricket ball','target marker'], 'Improve bowling accuracy by hitting a marked target zone.', ARRAY['Place a target marker on a good-length spot.', 'Mark your run-up of 5-8 paces.', 'Bowl aiming to hit the target consistently.', 'Record 20 deliveries and count hits.'], ARRAY['Keep your bowling arm high and straight.', 'Land your front foot to release the ball at the top of your arc.'], 'rZPTaA4RyXw', ARRAY['shoulders','core','legs'], 8),
('cricket', 'Catching Reflex Drill', 'Fielding', 'beginner', 10, ARRAY['tennis ball'], 'Sharpen reflexes with rapid close-range catching.', ARRAY['Stand 3 meters from a wall.', 'Throw the ball underarm against the wall at varying heights.', 'Catch with soft hands and absorb the ball.', 'Increase throw speed as you improve.'], ARRAY['Watch the ball all the way into your hands.', 'Give with the ball to avoid spills.'], 'rZPTaA4RyXw', ARRAY['forearms','core'], 6),
-- BASKETBALL
('basketball', 'Stationary Dribbling', 'Ball Handling', 'beginner', 10, ARRAY['basketball'], 'Build fundamental dribbling control with stationary drills.', ARRAY['Stand in an athletic stance with knees bent.', 'Dribble with your right hand for 30 seconds, then left.', 'Pound the ball hard and low to the floor.', 'Keep your eyes up, not on the ball.'], ARRAY['Pound the ball forcefully to build wrist strength.', 'Keep dribbles below knee height.'], 'rZPTaA4RyXw', ARRAY['forearms','core','calves'], 8),
('basketball', 'Figure-Eight Dribbling', 'Ball Handling', 'intermediate', 12, ARRAY['basketball'], 'Improve hand-eye coordination with figure-eight dribbling.', ARRAY['Stand with feet wider than shoulder-width.', 'Dribble the ball in a figure-eight pattern through your legs.', 'Alternate hands as the ball passes between your legs.', 'Increase speed while maintaining control.'], ARRAY['Stay low in an athletic stance.', 'Keep your dribble below knee height.'], 'rZPTaA4RyXw', ARRAY['core','forearms','quads'], 9),
('basketball', 'Form Shooting Close Range', 'Shooting', 'beginner', 15, ARRAY['basketball','basket (optional)'], 'Groove your shooting form from close range.', ARRAY['Stand 1-2 meters from the basket (or mark a target on a wall).', 'Set your feet shoulder-width apart.', 'Align your shooting elbow under the ball.', 'Shoot with one hand, focusing on wrist flick and follow-through.'], ARRAY['Keep your elbow in and aligned.', 'Snap your wrist down for backspin.'], 'rZPTaA4RyXw', ARRAY['shoulders','forearms','core'], 7),
('basketball', 'Defensive Slide Drill', 'Defense', 'intermediate', 10, ARRAY['cones'], 'Build lateral quickness and defensive stance endurance.', ARRAY['Set two cones 5 meters apart.', 'Assume a defensive stance and slide between cones without crossing feet.', 'Stay low and keep your hands active.', 'Repeat for 30-second intervals with 15 seconds rest.'], ARRAY['Never cross your feet — always slide.', 'Keep your hips low and back straight.'], 'rZPTaA4RyXw', ARRAY['glutes','quads','core'], 10),
-- TENNIS
('tennis', 'Shadow Swings', 'Groundstrokes', 'beginner', 10, ARRAY['tennis racket'], 'Build stroke technique with shadow swings for forehand and backhand.', ARRAY['Assume your ready position.', 'Practice the forehand swing motion slowly 20 times.', 'Repeat for the backhand (one-handed or two-handed).', 'Focus on unit turn, contact point, and follow-through.'], ARRAY['Keep your non-dominant hand on the throat of the racket for the unit turn.', 'Finish the swing across your body.'], 'rZPTaA4RyXw', ARRAY['core','shoulders','obliques'], 7),
('tennis', 'Wall Rally Drill', 'Groundstrokes', 'intermediate', 15, ARRAY['tennis racket','tennis ball','wall'], 'Sustain rallies against a wall to improve consistency and footwork.', ARRAY['Stand 4-5 meters from a wall.', 'Hit forehands and backhands alternately against the wall.', 'Aim for a consistent target spot.', 'Try to sustain 20+ consecutive hits.'], ARRAY['Split-step after each shot to reset.', 'Move your feet to always be in position.'], 'rZPTaA4RyXw', ARRAY['core','calves','shoulders'], 9),
('tennis', 'Serve Toss Practice', 'Serve', 'beginner', 12, ARRAY['tennis racket','tennis ball'], 'Isolate the ball toss to develop a consistent serve.', ARRAY['Stand at a service line or mark.', 'Practice tossing the ball to the same spot without hitting.', 'The ball should go up and come back down near your contact point.', 'Repeat 30 times, aiming for consistency.'], ARRAY['Keep your tossing arm extended and release high.', 'The toss should be slightly in front and to the side.'], 'rZPTaA4RyXw', ARRAY['shoulders','core'], 6),
('tennis', 'Agility Ladder Footwork', 'Footwork', 'intermediate', 10, ARRAY['agility ladder (or chalk)'], 'Improve on-court footwork speed and coordination.', ARRAY['Lay out an agility ladder (or draw one with chalk).', 'Run through using high-knees, two-feet-per-rung pattern.', 'Add lateral shuffles and icky-shuffle variations.', 'Complete 3 sets of each pattern.'], ARRAY['Stay on the balls of your feet.', 'Pump your arms to drive speed.'], 'rZPTaA4RyXw', ARRAY['calves','quads','core'], 11),
-- BADMINTON
('badminton', 'Shadow Footwork', 'Footwork', 'beginner', 10, ARRAY['badminton racket'], 'Practice court movement patterns without a shuttle.', ARRAY['Start at center court.', 'Lunge to each corner (forehand, backhand, front, back) and return to center.', 'Use chassé steps and a final lunge.', 'Repeat the pattern 20 times.'], ARRAY['Always return to center court after each movement.', 'Stay low and balanced in your lunges.'], 'rZPTaA4RyXw', ARRAY['quads','glutes','calves'], 9),
('badminton', 'Wall Rally Drill', 'Rally', 'intermediate', 12, ARRAY['badminton racket','shuttlecock','wall'], 'Sustain rallies against a wall to sharpen reflexes and control.', ARRAY['Stand 3 meters from a wall.', 'Hit the shuttle against the wall with clears and drives.', 'Aim for a consistent height and rhythm.', 'Try to sustain 30+ consecutive hits.'], ARRAY['Keep your racket up and ready.', 'Use your wrist for quick reactions.'], 'rZPTaA4RyXw', ARRAY['forearms','shoulders','core'], 10),
('badminton', 'Serve Practice', 'Serve', 'beginner', 10, ARRAY['badminton racket','shuttlecock'], 'Develop a reliable low and high serve.', ARRAY['Stand at the service line.', 'Practice 20 low serves aiming just over the net.', 'Practice 20 high serves aiming deep to the back court.', 'Focus on consistency and placement.'], ARRAY['Keep your racket foot back for the low serve.', 'Use a smooth, controlled motion for the high serve.'], 'rZPTaA4RyXw', ARRAY['forearms','shoulders'], 6),
('badminton', 'Smash Shadow Practice', 'Smash', 'intermediate', 10, ARRAY['badminton racket'], 'Groove the smash motion for power and timing.', ARRAY['Assume a side-on stance with racket up.', 'Rotate your hips and shoulders.', 'Snap your wrist down on the imaginary shuttle.', 'Follow through across your body. Repeat 20 times.'], ARRAY['Generate power from your core, not just your arm.', 'Contact the shuttle at the highest point.'], 'rZPTaA4RyXw', ARRAY['core','shoulders','obliques'], 8),
-- ATHLETICS
('athletics', 'Sprint Acceleration Drill', 'Sprinting', 'intermediate', 12, ARRAY['cones'], 'Develop explosive acceleration from a standing start.', ARRAY['Mark 30 meters with cones.', 'Start in a standing sprint position.', 'Sprint 30 meters at maximum effort.', 'Walk back and repeat 6 times with full recovery.'], ARRAY['Drive your arms hard for the first 10 meters.', 'Stay low and gradually rise over the first 20 meters.'], 'rZPTaA4RyXw', ARRAY['quads','glutes','calves','core'], 13),
('athletics', 'A-Skip Drill', 'Technique', 'beginner', 8, ARRAY[]::text[], 'Reinforce running mechanics with the A-skip drill.', ARRAY['Stand tall and engage your core.', 'Drive one knee up to hip height while skipping.', 'Snap the foot down under your center of mass.', 'Alternate legs with a rhythmic skip.'], ARRAY['Keep your posture tall.', 'Drive the knee up, do not let it float.'], 'rZPTaA4RyXw', ARRAY['calves','quads','core'], 9),
('athletics', 'Long Jump Approach Practice', 'Jumping', 'intermediate', 15, ARRAY[]::text[], 'Practice the approach run-up and takeoff for the long jump.', ARRAY['Mark a 15-20 meter approach.', 'Run in with accelerating strides.', 'Hit the takeoff board with a flat foot.', 'Drive the knee up and land softly. Repeat 8 times.'], ARRAY['Keep your eyes on the board during the approach.', 'Drive your free knee up at takeoff.'], 'rZPTaA4RyXw', ARRAY['quads','glutes','calves'], 10),
('athletics', 'Plank Core Stability', 'Strength', 'beginner', 8, ARRAY[]::text[], 'Build the core stability needed for efficient running.', ARRAY['Hold a forearm plank with body in a straight line.', 'Keep your glutes squeezed and core braced.', 'Hold for 30-60 seconds.', 'Rest 30 seconds and repeat 3 times.'], ARRAY['Do not let your hips sag or pike up.', 'Breathe steadily throughout.'], 'rZPTaA4RyXw', ARRAY['core','shoulders'], 6),
-- GENERAL FITNESS
('general_fitness', 'Bodyweight Squat', 'Strength', 'beginner', 10, ARRAY[]::text[], 'Build lower-body strength and mobility with bodyweight squats.', ARRAY['Stand with feet shoulder-width apart.', 'Lower your hips back and down as if sitting in a chair.', 'Keep your chest up and knees tracking over toes.', 'Drive through your heels to stand. Do 3 sets of 15.'], ARRAY['Keep your weight in your heels.', 'Go as deep as your mobility allows.'], 'rZPTaA4RyXw', ARRAY['quads','glutes','core'], 8),
('general_fitness', 'Push-Up', 'Strength', 'beginner', 10, ARRAY[]::text[], 'Develop upper-body pushing strength with push-ups.', ARRAY['Start in a high plank with hands under shoulders.', 'Lower your chest toward the floor, elbows at 45 degrees.', 'Keep your body in a straight line.', 'Push back up. Do 3 sets of 10-15.'], ARRAY['Keep your core tight to avoid sagging hips.', 'Scale by dropping to knees if needed.'], 'rZPTaA4RyXw', ARRAY['chest','triceps','core'], 8),
('general_fitness', 'Burpee', 'Conditioning', 'intermediate', 10, ARRAY[]::text[], 'Full-body conditioning with burpees.', ARRAY['From standing, drop into a squat and place hands on the floor.', 'Jump or step feet back to a plank.', 'Do a push-up (optional).', 'Jump feet to hands and explode up into a jump. Do 3 sets of 10.'], ARRAY['Keep a steady rhythm rather than sprinting.', 'Land softly from the jump.'], 'rZPTaA4RyXw', ARRAY['full_body'], 12),
('general_fitness', 'Mountain Climbers', 'Conditioning', 'intermediate', 8, ARRAY[]::text[], 'Build core and cardio endurance with mountain climbers.', ARRAY['Start in a high plank position.', 'Drive one knee toward your chest.', 'Alternate legs rapidly as if running in place.', 'Keep hips low and core engaged. Do 3 sets of 30 seconds.'], ARRAY['Keep your hips level — do not bounce them up.', 'Move from the core, not just the legs.'], 'rZPTaA4RyXw', ARRAY['core','shoulders','quads'], 11),
('general_fitness', 'High Plank Hold', 'Core', 'beginner', 6, ARRAY[]::text[], 'Build core and shoulder endurance with a high plank hold.', ARRAY['Start in a push-up position.', 'Hands under shoulders, body in a straight line.', 'Brace your core and glutes.', 'Hold for 30-60 seconds. Repeat 3 times.'], ARRAY['Do not let your hips sag.', 'Press the floor away to engage your shoulders.'], 'rZPTaA4RyXw', ARRAY['core','shoulders'], 6),
('general_fitness', 'Jumping Jacks', 'Cardio', 'beginner', 5, ARRAY[]::text[], 'Warm up the whole body with jumping jacks.', ARRAY['Stand with feet together and arms at your sides.', 'Jump feet out while raising arms overhead.', 'Jump back to start. ', 'Continue at a steady pace for 60 seconds. Repeat 3 times.'], ARRAY['Land softly with a slight knee bend.', 'Keep a steady rhythm.'], 'rZPTaA4RyXw', ARRAY['full_body'], 9)
ON CONFLICT DO NOTHING;

-- CHALLENGES -------------------------------------------------------------
INSERT INTO challenges (title, description, sport, category, target_value, target_unit, duration_days, difficulty, icon, points) VALUES
('7-Day Streak', 'Complete a workout every day for 7 days straight.', NULL, 'consistency', 7, 'workouts', 7, 'beginner', 'Flame', 150),
('30-Day Warrior', 'Train 20 days in a single month.', NULL, 'consistency', 20, 'workouts', 30, 'intermediate', 'Shield', 400),
('10K Steps Challenge', 'Hit 10,000 steps daily for 14 days.', NULL, 'steps', 140000, 'steps', 14, 'intermediate', 'Footprints', 300),
('Calorie Crusher', 'Burn 5,000 total calories through workouts.', NULL, 'calories', 5000, 'calories', 14, 'advanced', 'Flame', 350),
('Early Bird', 'Complete 10 morning workouts before 9 AM.', NULL, 'consistency', 10, 'workouts', 14, 'intermediate', 'Sunrise', 250),
('Hydration Hero', 'Drink 2.5L of water daily for 7 days.', NULL, 'hydration', 7, 'days', 7, 'beginner', 'Droplets', 200),
('Sprint Master', 'Complete 5 athletics sprint sessions.', 'athletics', 'sport', 5, 'sessions', 14, 'intermediate', 'Zap', 300),
('Sharp Shooter', 'Complete 5 basketball shooting sessions.', 'basketball', 'sport', 5, 'sessions', 14, 'intermediate', 'Target', 300)
ON CONFLICT DO NOTHING;

-- ACHIEVEMENTS -----------------------------------------------------------
INSERT INTO achievements (title, description, category, icon, threshold, metric, points, tier) VALUES
('First Workout', 'Complete your first workout.', 'workouts', 'Dumbbell', 1, 'total_workouts', 50, 'bronze'),
('Getting Started', 'Complete 10 workouts.', 'workouts', 'Activity', 10, 'total_workouts', 100, 'bronze'),
('Consistent', 'Complete 50 workouts.', 'workouts', 'Calendar', 50, 'total_workouts', 250, 'silver'),
('Century Club', 'Complete 100 workouts.', 'workouts', 'Trophy', 100, 'total_workouts', 500, 'gold'),
('Early Riser', 'Complete 5 morning workouts.', 'workouts', 'Sunrise', 5, 'morning_workouts', 150, 'bronze'),
('Calorie Burner', 'Burn 10,000 total calories.', 'calories', 'Flame', 10000, 'total_calories', 300, 'silver'),
('Step Master', 'Accumulate 100,000 steps.', 'steps', 'Footprints', 100000, 'total_steps', 300, 'silver'),
('Hydration Pro', 'Log hydration 30 times.', 'hydration', 'Droplets', 30, 'hydration_logs', 150, 'bronze'),
('Plan Follower', 'Complete 10 AI-generated workouts.', 'plans', 'ClipboardList', 10, 'plan_workouts', 200, 'silver'),
('Challenger', 'Join 3 challenges.', 'challenges', 'Swords', 3, 'challenges_joined', 150, 'bronze'),
('Champion', 'Complete 5 challenges.', 'challenges', 'Crown', 5, 'challenges_completed', 400, 'gold'),
('Video Analyst', 'Submit 3 videos for AI analysis.', 'video', 'Video', 3, 'videos_analyzed', 200, 'silver')
ON CONFLICT DO NOTHING;
